const {chromium}=require('C:/Users/mar15/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');const assert=require('node:assert/strict');
const base=process.env.UI_TEST_URL||'http://127.0.0.1:3187';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});const results={checks:[],errors:[],requests:[],accessibility:[]};
 const page=await browser.newPage();page.on('pageerror',e=>results.errors.push(e.message));
 let mode='success',release;
 const answer={answer:'Short answer: This is a browser test response.\n\nWhat I found:\n- The official source link is available below.',confidence:{canAnswer:true},sources:[{title:'CAB community information',isOfficialResource:true,sourceUrl:'https://sterlingranchcab.com/',excerpt:'Browser-test source excerpt used only to check the source disclosure layout.'}],actions:[{label:'Official CAB website',url:'https://sterlingranchcab.com/'}],sourceStatus:{exists:true,lastFetchedAt:new Date().toISOString()}};
 await page.route('**/api/community/ask',async route=>{const payload=route.request().postDataJSON();assert.equal(payload.isTest,true);results.requests.push(payload);if(mode==='hold')await new Promise(resolve=>release=resolve);if(mode==='error')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'The community assistant is temporarily unavailable.'})});else await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(answer)});});
 await page.route('**/api/rules/status',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(answer.sourceStatus)}));
 const shot=async name=>{await page.waitForTimeout(350);if(/sources|error/.test(name)){await page.addScriptTag({path:'artifacts/editorial-ui/tools/node_modules/axe-core/axe.min.js'});const violations=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});results.accessibility.push({state:name,violations});}await page.screenshot({path:'artifacts/editorial-ui/'+name+'.png',fullPage:true});};
 for(const viewport of ['desktop','mobile']){
  await page.setViewportSize(viewport==='desktop'?{width:1440,height:1100}:{width:390,height:844});await page.goto(base+'/community-assistant?test=1');
  assert(await page.locator('#testModeBanner').isVisible());if(await page.locator('#rulesStartOver').isVisible()) await page.locator('#rulesStartOver').click();
  await page.locator('#rulesQuestion').fill('Browser test: first question');await page.locator('#rulesQuestion').press('Shift+Enter');assert((await page.locator('#rulesQuestion').inputValue()).includes('\n'));await page.locator('#rulesQuestion').press('Enter');await page.locator('.rules-sources summary').waitFor();
  await page.locator('.rules-sources summary').focus();await page.keyboard.press('Enter');assert(await page.locator('.rules-sources').evaluate(e=>e.open));await shot('assistant-sources-'+viewport);
  const count=await page.locator('.rules-message').count();mode='hold';await page.locator('#rulesQuestion').fill('Browser test: follow-up');await page.locator('#rulesQuestion').press('Enter');await page.locator('.rules-typing').waitFor();assert(await page.locator('#rulesSend').isDisabled());assert((await page.locator('.rules-message').count())>count);assert(await page.locator('.rules-sources').evaluate(e=>e.open));await shot('assistant-loading-'+viewport);mode='success';release();await page.locator('.rules-typing').waitFor({state:'detached'});
  mode='error';await page.locator('#rulesQuestion').fill('Browser test: retry');await page.locator('#rulesQuestion').press('Enter');await page.locator('.rules-retry').waitFor();await page.waitForTimeout(350);assert((await page.locator('.rules-sources').count())===2);await shot('assistant-error-'+viewport);
  const users=await page.locator('.rules-message-user').count();mode='success';await page.locator('.rules-retry').click();await page.locator('.rules-retry').waitFor({state:'detached'});await page.waitForFunction(()=>!document.querySelector('#rulesSend').disabled);assert.equal(await page.locator('.rules-message-user').count(),users);assert.equal(await page.locator('.rules-sources').count(),3);
  await page.locator('#statusToggle').click();assert(await page.locator('#statusDetail').isVisible());await shot('assistant-status-'+viewport);await page.keyboard.press('Escape');assert.equal(await page.locator('#statusToggle').getAttribute('aria-expanded'),'false');assert(await page.locator('#statusToggle').evaluate(e=>e===document.activeElement));
  const links=await page.locator('.society-assistant-feedback a').evaluateAll(els=>els.map(e=>({href:e.getAttribute('href'),height:e.getBoundingClientRect().height})));assert(links.every(e=>e.href.startsWith('mailto:hello@ideakitchen.ai?')&&e.height>=44));await page.locator('.society-assistant-feedback').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/editorial-ui/feedback-'+viewport+'.png'});
  if(viewport==='mobile'){
   await page.locator('.society-menu').click();assert.equal(await page.locator('.society-menu').getAttribute('aria-expanded'),'true');assert(await page.locator('.society-nav a[href="/pool"]').isVisible());await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/editorial-ui/navigation-mobile.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('.society-menu').getAttribute('aria-expanded'),'false');assert(await page.locator('.society-menu').evaluate(e=>e===document.activeElement));assert(await page.locator('.society-nav a[href="/food-truck"]').isVisible());
  }
  await page.reload();assert((await page.locator('.rules-message-user').count())===3);results.checks.push(viewport+': loading, preserved history and expanded sources, Shift+Enter, Enter, error, retry without duplicate question, status Escape/focus, email drafts, mobile menu, session history');
 }
 await page.goto(base+'/openings');await page.locator('.opening-card').first().waitFor();await page.locator('#search').fill('HOKA');await page.waitForTimeout(200);assert((await page.locator('#result-count').innerText()).includes('1'));await page.locator('#clear-filters').click();assert.equal(await page.locator('#search').inputValue(),'');await page.locator('[data-open-tip]').first().click();assert(await page.locator('#tip-dialog').isVisible());await page.keyboard.press('Escape');assert(!await page.locator('#tip-dialog').isVisible());results.checks.push('Openings search, clear filters and tip dialog open/close; no tip submitted');
 await page.goto(base+'/?test=1');assert.equal(await page.locator('.briefing-search input[name=test]').inputValue(),'1');assert((await page.locator('.briefing-tags a').first().getAttribute('href')).includes('test=1'));results.checks.push('Briefing preserves test marker in Assistant form and shortcuts without submitting');
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'/community-assistant?test=1');assert.equal(await page.locator('.rules-message').first().evaluate(e=>getComputedStyle(e).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});results.checks.push('Reduced motion removes message animation');
 // A resident page still sends its normal marker; inspect code without making a resident request.
 const code=fs.readFileSync('public/rules-assistant.js','utf8');assert(code.includes('isTest: isTestMode'));assert(code.includes('get("test") === "1"'));
 // All links and visual feedback controls remain available without JavaScript.
 const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto(base+'/community-assistant?test=1');assert.equal(await nojs.locator('.society-nav a').count(),6);assert.equal(await nojs.locator('.society-assistant-feedback a').count(),2);await nojs.close();
 const axePath='artifacts/editorial-ui/tools/node_modules/axe-core/axe.min.js';
 if(fs.existsSync(axePath)){
  for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const route of ['/','/community-assistant?test=1','/food-truck','/calendar','/openings','/pool']){await page.goto(base+route);await page.waitForTimeout(1000);await page.addScriptTag({path:axePath});const audit=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});results.accessibility.push({width,route,violations:audit});}}
 }
 fs.writeFileSync('artifacts/editorial-ui/interaction-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({checks:results.checks,errors:results.errors,a11y:results.accessibility.map(r=>({width:r.width,route:r.route,state:r.state,violations:r.violations.map(v=>v.id)}))}));await browser.close();assert.equal(results.errors.length,0);assert(!results.accessibility.some(r=>r.violations.length));
})().catch(error=>{console.error(error);process.exit(1);});


