import {mergeCatalog,rootOf,searchPlaces} from './catalog.mjs';
import {descendants} from './discovery.mjs';
import {createDiscovery} from './discovery-ui.js';
import {createFocus} from './focus-ui.js';
import {futureOnly} from './focus.mjs';
import {createFutureMap} from './future-ui.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scrollBehavior=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function withPlaceTransition(update){if(!document.startViewTransition||scrollBehavior()==='auto'){update();return;}document.body.classList.add('place-transition');const transition=document.startViewTransition(update);transition.finished.catch(()=>{}).finally(()=>document.body.classList.remove('place-transition'));}
const read=async n=>{const r=await fetch(n);if(!r.ok)throw new Error(n);return r.json();};
const link=(a)=>/^https:\/\//.test(a.url||'')?`<a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.label||'Official details')} ↗</a>`:'';
try {
const [catalog,supplement,notes,local,area,layout,trails]=await Promise.all(['data/places.json','data/directory.json','data/visitor-notes.json','data/area-visit.json','area.json','data/layout.json','data/trails.json'].map(read));
const places=mergeCatalog(catalog,supplement,notes,local), byId=new Map(places.map(p=>[p.id,p])), roots=area.rootIds.map(id=>byId.get(id)), located=new Map(layout.roots.filter(p=>p.imagePixels).map(p=>[p.id,p]));
const heroes=['sterling-center','overlook','burns','prospect-park'], children=id=>places.filter(p=>p.parentId===id&&!p.future), summary=p=>p.summary||p.description||'', number=id=>String(area.rootIds.indexOf(id)+1).padStart(2,'0');
// Artwork registration is deliberately separate from source coordinates.
// The painting is an illustrated overview, not georeferenced navigation.
const artAnchors={'sterling-center':[895,315],overlook:[1060,365],burns:[785,590],'prospect-park':[374,933]};
const point=id=>!source&&artAnchors[id]?artAnchors[id]:located.get(id)?.imagePixels;
let selected='sterling-center', view='neighborhood', group=0, detail=null, opened=true, zoom=1, source=false;
const models={'sterling-center':'sterling-center.png',overlook:'overlook-model.png',burns:'burns-model.png','prospect-park':'prospect-model.png'};
function groups(id){const kids=children(id);if(id==='sterling-center')return [{name:'Eat & gather',caption:'Ranch Social & its places',ids:['ranch-social'],symbol:'01'},{name:'Care & wellbeing',caption:'Health, dental, eyes & spa',ids:['uchealth','lake-family-dental','sterling-eyecare','rave'],symbol:'02'},{name:'Community',caption:'Information & CAB offices',ids:['info-center','cab-office'],symbol:'03'}];if(id==='overlook')return [{name:'Swim',caption:'Pool & splash pad',ids:['overlook-pool','overlook-splash'],symbol:'01'},{name:'Move',caption:'Fitness center',ids:['overlook-fitness'],symbol:'02'},{name:'Gather',caption:'Hall, pavilions & rentals',ids:kids.filter(p=>!['overlook-pool','overlook-splash','overlook-fitness'].includes(p.id)).map(p=>p.id),symbol:'03'}];return [{name:'Explore',caption:`${kids.length} things to know`,ids:kids.map(p=>p.id),symbol:'01'}];}
function setView(next){view=next;$('.skip').href=view==='future'?'#future-note':'#place-note';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));['neighborhood','inside','walks','future'].forEach(v=>$('#'+v+'-panel').hidden=(v==='inside'?'place':v)!==view);document.body.dataset.view=view;$('.more-to-explore').hidden=view==='future';$('#all-places').hidden=view==='future';$('#search-results').hidden=true;$('#search').value='';$('#search').placeholder=view==='future'?'Search future projects…':'Coffee, a playground, a place…';$('#search').setAttribute('aria-label',view==='future'?'Find a future project':'Find a place or amenity');$('#inventory-count').textContent=view==='future'?futureOnly(places).length+' planned listings · '+futureOnly(places).filter(p=>!byId.get(p.parentId)?.future).length+' projects':places.length+' listings · '+roots.length+' destinations · '+trails.routes.length+' walking guides';if(view==='place')renderPlace();if(view==='walks')renderWalks();if(view==='future')renderFuture();$('#status').textContent=view==='neighborhood'?'Full Sterling Ranch area':view==='place'?byId.get(selected).name:view==='walks'?'Three walking guides':'Planned places';if(view==='neighborhood')discovery.render();}
function marker(p){const xy=point(p.id);return `<button class="map-label ${heroes.includes(p.id)?'':'minor'} ${selected===p.id?'selected':''}" data-select="${p.id}" aria-label="${esc(p.name)}" aria-pressed="${selected===p.id}" style="left:${xy[0]/15.36}%;top:calc(${xy[1]/10.24}% - 15px)"><span class="number">${number(p.id)}</span><span class="name">${esc(p.name.replace('Regional Park','Park').replace('The Overlook Clubhouse','The Overlook'))}</span></button>`;}
function renderMap(){const p=byId.get(selected);$('#map-labels').innerHTML=roots.filter(p=>located.has(p.id)).map(marker).join('');$('#place-note').innerHTML=`<div class="selected-portrait">${models[p.id]?`<img src="assets/${models[p.id]}" alt="" aria-hidden="true">`:''}<div><p class="eyebrow">${esc(p.village||'STERLING RANCH')} / ${located.has(p.id)?'EXPLORE THIS PLACE':'DIRECTORY · LOCATION TO CONFIRM'}</p><h2>${esc(p.name)}</h2></div></div><p class="description">${esc(summary(p))}</p><button class="primary" data-open="${p.id}">${models[p.id]?'Open it up':'Explore this place'} <span>↗</span></button>`;$('#destination-strip').innerHTML=heroes.map(id=>{const p=byId.get(id);return `<button class="destination ${selected===id?'selected':''}" data-select="${id}"><span>${number(id)}</span><div><strong>${esc(p.name.replace('Regional Park','Park'))}</strong><small>${esc(p.village)} · ${descendants(id,places).length} ${descendants(id,places).length===1?'amenity':'places & amenities'}</small></div></button>`;}).join('');discovery.render();}
function select(id,open=false){const p=byId.get(id);if(!p)return;$('#search-results').hidden=true;$('#search').value='';if(p.future){discovery.collapse();setView('future');futureMap.select(id);return;}selected=rootOf(id,byId).id;discovery.reveal(selected);group=0;detail=id===selected?null:id;opened=true;camera.place(selected,byId.get(selected).name);renderMap();if(open){withPlaceTransition(()=>{setView('place');$('#experience').scrollIntoView({block:'start',behavior:'instant'});const focusTarget=detail?$('#directory'):$('.model-heading');focusTarget.setAttribute('tabindex','-1');focusTarget.focus({preventScroll:true});if(detail&&innerWidth<=720)focusTarget.scrollIntoView({block:'start',behavior:'instant'});});}else{setView('neighborhood');$('#place-note').focus({preventScroll:true});$('#landscape').scrollIntoView({block:'start',behavior:scrollBehavior()});}}
function focusMap(){camera.refresh();}
function row(p){const sub=children(p.id);return `<button class="tenant" data-detail="${p.id}"><span class="initial">${esc(p.name[0])}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.tags?.slice(0,3).join(' · ')||'Details & sources')}</small></span><b>↗</b></button>${sub.length?`<details class="nested" open><summary>Within ${esc(p.name)} <small>${sub.length} places & amenities</small></summary>${sub.map(row).join('')}</details>`:''}`;}
function visit(p){const points=p.highlights?.length?p.highlights:(p.visitNotes?.length?p.visitNotes:(p.facts||[]).map(f=>typeof f==='string'?f:f.text));const unique=[...new Set(points)].filter(Boolean).slice(0,7);const sources=[...(p.actions||[]),...(p.sources||[])].filter((a,i,arr)=>arr.findIndex(b=>b.url===a.url)===i);return `${p.address?`<p class="address">${esc(p.address)}</p>`:''}${p.access?`<p class="description">${esc(p.access)}</p>`:''}${unique.length?`<ul class="visit-list">${unique.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}${p.note?`<p class="source-footnote">${esc(p.note)}</p>`:''}<div class="source-actions">${sources.map(link).join('')}</div>`;}
function renderPlace(){const p=byId.get(selected), g=groups(selected);group=Math.min(group,g.length-1);const hasModel=!!models[selected], building=$('#building');$('#model-kicker').textContent=(p.village||'Sterling Ranch')+' / PLACES WITHIN PLACES';$('#model-title').textContent=p.name;building.classList.toggle('clubhouse',selected!=='sterling-center');building.classList.toggle('landscape-detail',!hasModel);$('#building-intact').src='assets/'+(models[selected]||'full-landscape.png');$('#building-intact').alt=hasModel?'Architectural illustration of '+p.name:'Full-area illustration; exact building detail is not available for '+p.name;$('#model-stage').classList.toggle('closed',!opened);building.style.setProperty('--opening',opened?1:0);$('#roof-toggle').textContent=opened?'Bring it together ↓':'Explore what’s here ↑';$('#roof-toggle').setAttribute('aria-pressed',String(opened));$('#model-caption').textContent=selected==='sterling-center'?'Directory groups · not room locations':hasModel?'Illustrated model · select an amenity below':'Place detail · no invented building model';$('#reveal-groups').innerHTML=g.map((c,i)=>`<button class="group-token" data-group="${i}" aria-pressed="${group===i}"><span>${c.symbol}</span><strong>${esc(c.name)}</strong><small>${esc(c.caption)}</small></button>`).join('');const xy=artAnchors[selected]||located.get(selected)?.imagePixels;$('#context-dot').hidden=!xy;if(xy){$('#context-dot').style.setProperty('--map-x',xy[0]/15.36+'%');$('#context-dot').style.setProperty('--map-y',xy[1]/10.24+'%');}renderDirectory();}
function renderDirectory(){const p=byId.get(detail||selected);$('#reveal-groups').inert=!opened;if(detail){$('#directory').innerHTML=`<button class="mini-back" data-detail-back>← Everything at ${esc(byId.get(selected).name)}</button><p class="eyebrow">${esc(p.parentName||byId.get(selected).name)}</p><h2>${esc(p.name)}</h2><p class="description">${esc(summary(p))}</p>${visit(p)}${children(p.id).map(row).join('')}`;}else{const g=groups(selected);$('#directory').innerHTML=`<p class="eyebrow">GOOD TO KNOW BEFORE YOU GO</p><h2>${esc(p.name)}</h2><p class="description">${esc(summary(p))}</p>${p.address?`<p class="address">${esc(p.address)}</p>`:''}<div class="category-tabs" role="group" aria-label="What’s here">${g.map((c,i)=>`<button data-group="${i}" aria-pressed="${group===i}">${esc(c.name)}</button>`).join('')}</div><p class="group-intro">${esc(g[group].caption)}</p>${g[group].ids.map(id=>byId.get(id)).filter(Boolean).map(row).join('')}<details class="nested"><summary>Plan your visit & sources</summary>${visit(p)}</details>${!located.has(p.id)?'<p class="source-footnote">Included in the directory. A precise map position is still to be confirmed.</p>':''}`;}$('#directory').scrollTop=0;}
function routeSvg(r){const vb=r.viewBox||trails.overview;return `<svg class="route-sketch" viewBox="${vb.join(' ')}" role="img" aria-label="${esc(r.name)} on CAB’s walking map"><image href="assets/cab-trail-map.png" width="${trails.imageSize[0]}" height="${trails.imageSize[1]}"/><g fill="none" stroke="${esc(r.color)}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${r.paths.map(path=>`<polyline points="${path.map(p=>p.join(',')).join(' ')}"/>`).join('')}</g>${(trails.annotationUpdates||[]).map(a=>`<g><rect x="${a.box[0]}" y="${a.box[1]}" width="${a.box[2]}" height="${a.box[3]}" fill="#f0f2e8"/><text x="${a.box[0]+3}" y="${a.box[1]+10}" fill="#24443f" font-size="7" font-family="Arial,sans-serif">${a.lines.map((t,i)=>`<tspan x="${a.box[0]+3}" dy="${i?10:0}">${esc(t)}</tspan>`).join('')}</text></g>`).join('')}</svg>`;}
function renderWalks(){$('#walk-list').innerHTML=trails.routes.map(r=>`<article class="walk-card" data-route-id="${r.id}">${routeSvg(r)}<p class="eyebrow">${esc(r.area)} / ${esc(r.type)}</p><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="route-stats"><span>${r.miles} mi</span><span>${Math.round(r.miles*20)}–${Math.round(r.miles*30)} min before stops</span></div><p><strong>Start:</strong> ${esc(r.start)}</p><button class="primary" data-route="${r.id}">Open walking guide <span>↗</span></button></article>`).join('');}
function showRoute(id){const r=trails.routes.find(r=>r.id===id);$('#route-content').innerHTML=`<p class="eyebrow">${esc(r.area)} / CAB WALKING GUIDE</p><h2 id="route-title">${esc(r.name)}</h2>${routeSvg(r)}<p>${esc(r.description)}</p><p class="route-distance">${r.miles} miles · ${esc(trails.distanceNote)}</p><p><strong>Start:</strong> ${esc(r.start)}</p><ol class="route-steps">${r.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p><strong>Finish:</strong> ${esc(r.finish)}</p><div class="route-nearby">${r.nearbyPlaceIds.filter(id=>byId.has(id)).map(id=>`<button data-route-place="${id}">${esc(byId.get(id).name)} ↗</button>`).join('')}</div><p class="source-footnote">${esc(trails.mapNote)}</p><div class="source-actions">${link({label:'Official CAB trail map',url:trails.source.url})}${link({label:'Current trail information',url:trails.source.listingUrl})}</div>`;$('#route-dialog').showModal();}
function projectDetails(p){const update=local.projects.find(x=>x.id===p.id);const nested=places.filter(c=>c.parentId===p.id&&c.future);return `<article class="project-card" id="project-${p.id}" data-project-id="${p.id}"><span class="project-status">${esc(update?.status||p.status||'Planned')}</span><p class="eyebrow">${esc(p.village||'STERLING RANCH')}</p><h3>${esc(update?.name||p.name)}</h3><p>${esc(update?.summary||summary(p))}</p>${update?`<ul class="visit-list">${update.details.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><div class="source-actions">${link({label:update.sourceLabel,url:update.url})}</div><p class="source-footnote">${esc(update.locationNote)}</p>`:visit(p)}${nested.length?`<details class="nested"><summary>Plans within this place · ${nested.length}</summary>${nested.map(c=>`<h4 id="project-detail-${c.id}">${esc(c.name)}</h4><p>${esc(summary(c))}</p>${visit(c)}`).join('')}</details>`:''}</article>`;}
function renderFuture(){futureMap.render();}
function renderDirectoryGrid(){const villages=[...new Set(roots.map(p=>p.village||'Sterling Ranch'))];$('#area-filter').innerHTML='<option value="all">Every area</option>'+villages.map(v=>`<option>${esc(v)}</option>`).join('');const draw=()=>{$('#all-places').innerHTML=roots.filter(p=>$('#area-filter').value==='all'||p.village===$('#area-filter').value).map(p=>`<button class="place-card" data-open="${p.id}" data-root-id="${p.id}"><span class="eyebrow">${esc(p.village||'Sterling Ranch')}</span><strong>${esc(p.name)}</strong><small>${descendants(p.id,places).length?descendants(p.id,places).length+(descendants(p.id,places).length===1?' amenity inside':' places & amenities inside'):'Details & official sources'}${located.has(p.id)?'':' · map position to confirm'}</small><span class="card-arrow">↗</span></button>`).join('');};$('#area-filter').addEventListener('change',draw);draw();}
const futureMap=createFutureMap({places,roots,point:id=>artAnchors[id]||located.get(id)?.imagePixels,details:projectDetails});
const camera=createFocus({roots,point,onReset:()=>discovery.reset()});
const discovery=createDiscovery({places,roots,trails,models,located,selected:()=>selected,select,showRoute,setView,routeSvg,focusVillage:name=>camera.village(name),focusState:()=>camera.state()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.select)select(b.dataset.select);if(b.dataset.open)select(b.dataset.open,true);if(b.dataset.detail){detail=b.dataset.detail;renderDirectory();$('#directory').focus({preventScroll:true});}if('detailBack'in b.dataset){detail=null;renderDirectory();$('#directory').focus({preventScroll:true});}if('group'in b.dataset){group=Number(b.dataset.group);detail=null;renderPlace();$('.category-tabs [data-group="'+group+'"]')?.focus({preventScroll:true});}if(b.dataset.route)showRoute(b.dataset.route);if(b.dataset.routePlace){$('#route-dialog').close();select(b.dataset.routePlace,true);}if(b.dataset.close)$('#'+b.dataset.close).close();});
$('#back-to-map').onclick=()=>{setView('neighborhood');focusMap();$('#place-note').focus({preventScroll:true});};$('#context-map').onclick=()=>{setView('neighborhood');focusMap();$('#place-note').focus({preventScroll:true});};$('#roof-toggle').onclick=()=>{opened=!opened;renderPlace();};$('#zoom-in').onclick=()=>camera.zoom(.25);$('#zoom-out').onclick=()=>camera.zoom(-.25);$('#reset-map').onclick=()=>{camera.clear();discovery.reset();};
$('#source-toggle').onclick=()=>{source=!source;$('#source-art').hidden=!source;$('#source-toggle').setAttribute('aria-pressed',String(source));$('.map-topnote small').textContent=source?'Saved source geometry · approximate facility coordinates':'Illustrated overview · approximate placement';renderMap();focusMap();};
$('#about-open').onclick=$('#sources-open').onclick=()=>$('#about-dialog').showModal();
$('#search').addEventListener('input',()=>{const q=$('#search').value.trim(), found=searchPlaces(view==='future'?futureOnly(places):places,q);$('#search-results').hidden=!q;$('#search-results').innerHTML=found.length?found.map(p=>`<button data-open="${p.id}"><strong>${esc(p.name)}</strong><small>${esc(p.future?'Coming soon':p.parentName||p.village||'Sterling Ranch')}</small></button>`).join('') :(view==='future'?'<p>No matching future project. Try “school”, “library” or a village name.</p>':'<p>No saved match. Try a place name, “pickleball” or “playground”.</p>');});$('#search').addEventListener('keydown',e=>{if(e.key==='Escape')$('#search-results').hidden=true;});
$('#inventory-count').textContent=`${places.length} listings · ${roots.length} destinations · ${trails.routes.length} walking guides`;document.body.dataset.coverage='full-saved-atlas-area';document.body.dataset.placeCount=places.length;document.body.dataset.rootCount=roots.length;document.body.dataset.routeCount=trails.routes.length;
const art=$('#landscape-art');const loaded=()=>$('#image-status').hidden=art.complete&&art.naturalWidth>0;art.addEventListener('load',loaded);art.addEventListener('error',()=>{$('#image-status').textContent='The illustration could not load. The directory and source map are still available.';$('#source-art').hidden=false;});loaded();renderMap();renderDirectoryGrid();const params=new URLSearchParams(location.search);if(byId.has(params.get('place')))select(params.get('place'),true);else if(['walks','future'].includes(params.get('view')))setView(params.get('view'));else if(params.get('lens')==='future')setView('future');else if(params.get('village')){camera.village(params.get('village'));discovery.render();}
} catch(error){$('#image-status').hidden=false;$('#image-status').textContent='The atlas could not load its saved directory. Please reload.';console.error(error);}
