import {visitCard} from './visit-ui.js';
import {readNavigation,navigationQuery} from './navigation.mjs';
import {hotspotMarkup,positionHotspots} from './hotspots.js';
import {inVillage} from './focus.mjs';
import {mergeCatalog,rootOf,searchPlaces} from './catalog.mjs';
import {descendants} from './discovery.mjs';
import {createDiscovery} from './discovery-ui.js';
import {createFocus} from './focus-ui.js';
import {futureOnly} from './focus.mjs';
import {createFutureMap} from './future-ui.js';
import {modelRail,modelComparison} from './model-ui.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scrollBehavior=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function withPlaceTransition(update){if(!document.startViewTransition||scrollBehavior()==='auto'){update();return;}document.body.classList.add('place-transition');const transition=document.startViewTransition(update);transition.finished.catch(()=>{}).finally(()=>document.body.classList.remove('place-transition'));}
const read=async n=>{const r=await fetch(n);if(!r.ok)throw new Error(n);return r.json();};
const link=(a)=>/^https:\/\//.test(a.url||'')?`<a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.label||'Official details')} ↗</a>`:'';
try {
const [catalog,supplement,notes,local,area,layout,trails,modelRegistry]=await Promise.all(['data/places.json','data/directory.json','data/visitor-notes.json','data/area-visit.json','area.json','data/layout.json','data/trails.json','data/models.json'].map(read));
const places=mergeCatalog(catalog,supplement,notes,local), byId=new Map(places.map(p=>[p.id,p])), roots=area.rootIds.map(id=>byId.get(id)), located=new Map(layout.roots.filter(p=>p.imagePixels).map(p=>[p.id,p]));
const modelEntries=(modelRegistry.models||[]).filter(m=>m&&m.id&&m.asset), modelById=new Map(modelEntries.map(m=>[m.id,m]));
const heroes=['sterling-center','overlook','burns','prospect-park'], children=id=>places.filter(p=>p.parentId===id&&!p.future), summary=p=>p.summary||p.description||'', number=id=>String(area.rootIds.indexOf(id)+1).padStart(2,'0');
// Artwork registration is deliberately separate from source coordinates.
// The painting is an illustrated overview, not georeferenced navigation.
const artAnchors={'sterling-center':[895,315],overlook:[1060,365],burns:[785,590],'prospect-park':[374,933]};
const point=id=>!source&&artAnchors[id]?artAnchors[id]:located.get(id)?.imagePixels;
let navigationReady=false,restoring=false,returnMap=null,pendingReturnMap=null;
let selected='sterling-center', view='neighborhood', group=0, detail=null, opened=true, zoom=1, source=false, showingReference=false;
const models=Object.fromEntries(modelEntries.map(m=>[m.id,m.asset]));
function groups(id){const kids=children(id);if(id==='sterling-center')return [{name:'Eat & gather',caption:'Ranch Social & its places',ids:['ranch-social'],symbol:'01'},{name:'Care & wellbeing',caption:'Health, dental, eyes & spa',ids:['uchealth','lake-family-dental','sterling-eyecare','rave'],symbol:'02'},{name:'Community',caption:'Information & CAB offices',ids:['info-center','cab-office'],symbol:'03'}];if(id==='overlook')return [{name:'Swim',caption:'Pool & splash pad',ids:['overlook-pool','overlook-splash'],symbol:'01'},{name:'Move',caption:'Fitness center',ids:['overlook-fitness'],symbol:'02'},{name:'Gather',caption:'Hall, pavilions & rentals',ids:kids.filter(p=>!['overlook-pool','overlook-splash','overlook-fitness'].includes(p.id)).map(p=>p.id),symbol:'03'}];return [{name:kids.length?'Explore':'Park notes',caption:kids.length?`${kids.length} ${kids.length===1?'thing':'things'} to know`:'Visit details and official sources',ids:kids.map(p=>p.id),symbol:'01'}];}
function setView(next){view=next;$('.skip').href=view==='future'?'#future-note':view==='place'?'#directory':view==='walks'?'#walks-panel':'#neighborhood-panel';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));['neighborhood','inside','walks','future'].forEach(v=>$('#'+v+'-panel').hidden=(v==='inside'?'place':v)!==view);document.body.dataset.view=view;$('.more-to-explore').hidden=view==='future';$('#all-places').hidden=view==='future';closeSearch();$('#search').placeholder=view==='future'?'Search future projects…':'Coffee, a playground, a place…';$('#search').setAttribute('aria-label',view==='future'?'Find a future project':'Find a place or amenity');$('#inventory-count').textContent=view==='future'?futureOnly(places).length+' planned listings · '+futureOnly(places).filter(p=>!byId.get(p.parentId)?.future).length+' projects':places.length+' listings · '+roots.length+' destinations · '+trails.routes.length+' walking guides';if(view==='place')renderPlace();if(view==='walks')renderWalks();if(view==='future')renderFuture();$('#status').textContent=view==='neighborhood'?'Full Sterling Ranch area':view==='place'?byId.get(selected).name:view==='walks'?'Three walking guides':'Planned places';if(view==='neighborhood')discovery.render();saveNavigation();}
function marker(p){const xy=point(p.id);return `<button class="map-label ${heroes.includes(p.id)?'':'minor'} ${selected===p.id?'selected':''}" data-select="${p.id}" aria-label="${esc(p.name)}" aria-pressed="${selected===p.id}" style="left:${xy[0]/15.36}%;top:calc(${xy[1]/10.24}% - 15px)"><span class="number">${number(p.id)}</span><span class="name">${esc(p.name.replace('Regional Park','Park').replace('The Overlook Clubhouse','The Overlook'))}</span></button>`;}
function renderMap(){const p=byId.get(selected);$('#map-labels').innerHTML=roots.filter(p=>located.has(p.id)).map(marker).join('');$('#place-note').innerHTML=`<div class="selected-portrait">${models[p.id]?`<img src="assets/${models[p.id]}" alt="" aria-hidden="true">`:''}<div><p class="eyebrow">${esc(p.village||'STERLING RANCH')} / ${located.has(p.id)?'EXPLORE THIS PLACE':'DIRECTORY · LOCATION TO CONFIRM'}</p><h2>${esc(p.name)}</h2></div></div><p class="description">${esc(summary(p))}</p><button class="primary" data-open="${p.id}">${models[p.id]?'Open it up':'Explore this place'} <span>↗</span></button>`;$('#destination-strip').innerHTML=heroes.map(id=>{const p=byId.get(id);return `<button class="destination ${selected===id?'selected':''}" data-select="${id}"><span>${number(id)}</span><div><strong>${esc(p.name.replace('Regional Park','Park'))}</strong><small>${esc(p.village)} · ${descendants(id,places).length} ${descendants(id,places).length===1?'amenity':'places & amenities'}</small></div></button>`;}).join('');discovery.render();}
function select(id,open=false){
 const p=byId.get(id);if(!p)return;closeSearch();
 if(view==='neighborhood'&&open){returnMap=pendingReturnMap||{discovery:discovery.state(),focus:camera.snapshot()};pendingReturnMap=null;}
 if(p.future){discovery.collapse();setView('future');futureMap.select(id);saveNavigation();return;}
 selected=rootOf(id,byId).id;showingReference=false;discovery.reveal(selected);group=0;detail=id===selected?null:id;opened=true;
 camera.place(selected,byId.get(selected).name);renderMap();
 if(open){withPlaceTransition(()=>{setView('place');$('#experience').scrollIntoView({block:'start',behavior:'instant'});const target=detail?$('#directory'):$('.model-heading');target.setAttribute('tabindex','-1');target.focus({preventScroll:true});if(detail&&innerWidth<=720)target.scrollIntoView({block:'start',behavior:'instant'});saveNavigation();});}
 else{setView('neighborhood');$('#place-note').focus({preventScroll:true});$('#landscape').scrollIntoView({block:'start',behavior:scrollBehavior()});saveNavigation();}
}
function focusMap(){camera.refresh();}
function row(p){const sub=children(p.id);return `<button class="tenant" data-detail="${p.id}"><span class="initial">${esc(p.name[0])}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.tags?.slice(0,3).join(' · ')||'Details & sources')}</small></span><b>↗</b></button>${sub.length?`<details class="nested" open><summary>Within ${esc(p.name)} <small>${sub.length} places & amenities</small></summary>${sub.map(row).join('')}</details>`:''}`;}
function visit(p){return visitCard(p,{parent:byId.get(p.parentId)});}
function renderPlace(){const p=byId.get(selected), g=groups(selected), model=modelById.get(selected);group=Math.min(group,g.length-1);const hasModel=!!model, building=$('#building'), hasPhoto=Boolean(model?.referenceImage), mediaPhoto=hasPhoto&&showingReference;$('#model-kicker').textContent=(p.village||'Sterling Ranch')+' / PLACES UP CLOSE';$('#model-title').textContent=p.name;const currentArea=discovery.state().village;const railEntries=modelEntries.filter(m=>inVillage(byId.get(m.id),currentArea));$('#model-rail').innerHTML=modelRail(railEntries,places,selected);$('#place-picker').innerHTML=roots.filter(p=>inVillage(p,currentArea)||p.id===selected).map(p=>'<option value="'+esc(p.id)+'" '+(p.id===selected?'selected':'')+'>'+esc(p.name)+'</option>').join('');$('#return-context').textContent=returnMap?.discovery?.village&&returnMap.discovery.village!=='all'?'Back to '+returnMap.discovery.village:'Back to the map';const selectedModelButton=$('#model-rail [aria-pressed="true"]');if(selectedModelButton)$('#model-rail').scrollLeft=Math.max(0,selectedModelButton.offsetLeft-$('#model-rail').clientWidth/2+selectedModelButton.offsetWidth/2);building.classList.toggle('clubhouse',selected!=='sterling-center');building.classList.toggle('landscape-detail',!hasModel);building.classList.toggle('reference-photo',mediaPhoto);$('#building-intact').src=mediaPhoto?model.referenceImage:'assets/'+(model?.asset||'full-landscape.png');$('#building-intact').alt=mediaPhoto?`Official reference photo of ${p.name}`:hasModel?model.alt:'Full-area illustration; exact building detail is not available for '+p.name;$('#model-stage').classList.toggle('photo-model',hasPhoto);const canOpen=selected==='sterling-center';$('#model-stage').classList.toggle('closed',canOpen&&!opened);building.style.setProperty('--opening',canOpen&&opened?1:0);$('#roof-toggle').hidden=!canOpen;$('#roof-toggle').textContent=opened?'Bring it together ↓':'Explore what’s here ↑';$('#roof-toggle').setAttribute('aria-pressed',String(opened));$('#model-caption').textContent=selected==='sterling-center'?'Directory groups · not room locations':hasModel?(mediaPhoto?'Official reference photograph':'Illustrated place detail'):'Place detail · no invented building model';$('#model-comparison').innerHTML=modelComparison(model,mediaPhoto);$('#reveal-groups').innerHTML=g.map((c,i)=>`<button class="group-token" data-group="${i}" aria-pressed="${group===i}"><span>${c.symbol}</span><strong>${esc(c.name)}</strong><small>${esc(c.caption)}</small></button>`).join('');const xy=artAnchors[selected]||located.get(selected)?.imagePixels;$('#context-dot').hidden=!xy;if(xy){$('#context-dot').style.setProperty('--map-x',xy[0]/15.36+'%');$('#context-dot').style.setProperty('--map-y',xy[1]/10.24+'%');}renderDirectory();renderHotspots();}
function renderDirectory(){
 const p=byId.get(detail||selected);$('#reveal-groups').inert=!opened;
 const help='<button class="jump-to-art" type="button" data-see-art>See the illustration ↑</button>';
 if(detail){$('#directory').innerHTML='<button class="mini-back" data-detail-back>← Everything at '+esc(byId.get(selected).name)+'</button><p class="eyebrow">'+esc(p.parentName||byId.get(selected).name)+'</p><h2>'+esc(p.name)+'</h2><p class="description">'+esc(summary(p))+'</p>'+visit(p)+children(p.id).map(row).join('')+help;}
 else{const g=groups(selected);$('#directory').innerHTML='<p class="eyebrow">'+esc(p.name)+'</p><h2>Plan your visit.</h2><button class="amenity-jump" data-amenities-jump>Explore what’s here ↓</button><p class="description">'+esc(summary(p))+'</p>'+visit(p)+'<section class="inside-amenities"><h3>Explore what’s here</h3><div class="category-tabs" role="group" aria-label="What’s here">'+g.map((c,i)=>'<button data-group="'+i+'" aria-pressed="'+(group===i)+'">'+esc(c.name)+'</button>').join('')+'</div>'+g[group].ids.map(id=>byId.get(id)).filter(Boolean).map(row).join('')+'</section>'+(!located.has(p.id)?'<p class="source-footnote">In the directory; map position still to confirm.</p>':'')+help;}
 $('#directory').scrollTop=0;
}
function renderHotspots(){
 const markup=showingReference?'':hotspotMarkup(selected,detail,places);$('#model-hotspots').innerHTML=markup;
 $('#hotspot-hint').hidden=!markup;$('#hotspot-hint').textContent='Select a numbered feature to explore it.';
 positionHotspots($('#building'),$('#building-intact'));
}
function openDetail(id){detail=id;renderDirectory();renderHotspots();$('#directory').focus({preventScroll:true});if(innerWidth<=720)$('#directory').scrollIntoView({block:'start',behavior:scrollBehavior()});saveNavigation();}
function returnToMap(){
 if(returnMap){discovery.restore(returnMap.discovery);const f=returnMap.focus;if(f?.target?.kind==='place'&&byId.has(f.target.id))f.target.name=byId.get(f.target.id).name;camera.restore(f);}
 setView('neighborhood');renderMap();const target=discovery.state().unfolded?$('#unfold-sheets'):$('#landscape');target.scrollIntoView({block:'start',behavior:scrollBehavior()});const focusTarget=discovery.state().unfolded?$('#unfold-sheets button'):$('#place-note');focusTarget?.focus({preventScroll:true});saveNavigation();
}
function snapshotNavigation(){return {view,place:detail||selected,group,photo:showingReference,source,opened,discovery:discovery.state(),focus:camera.snapshot(),future:futureMap.state(),returnMap};}
function saveNavigation(replace=false){
 if(!navigationReady||restoring)return;
 queueMicrotask(()=>{if(restoring)return;const state=snapshotNavigation(),query=navigationQuery(state);if(location.search!==query||replace)history[replace?'replaceState':'pushState']({atlas:state},'',location.pathname+query);});
}
function restoreNavigation(s){
 restoring=true;
 const target=byId.get(s.place);selected=target&&!target.future?rootOf(target.id,byId).id:'sterling-center';detail=target&&target.id!==selected&&!target.future?target.id:null;
 group=s.group||0;opened=s.opened!==false;source=!!s.source;showingReference=!!s.photo;returnMap=s.returnMap||null;
 $('#source-art').hidden=!source;$('#source-toggle').setAttribute('aria-pressed',String(source));
 discovery.restore(s.discovery||{});const focus=s.focus||{target:null,manual:1};if(focus.target?.kind==='place'){const p=byId.get(focus.target.id);focus.target=p?{kind:'place',id:rootOf(p.id,byId).id,name:rootOf(p.id,byId).name}:null;}camera.restore(focus);
 futureMap.restore(s.future||{});renderMap();setView(['neighborhood','place','walks','future'].includes(s.view)?s.view:'neighborhood');
 restoring=false;
}
function closeSearch(){ $('#search-announcement').textContent='';$('#search-results').hidden=true;$('#search').setAttribute('aria-expanded','false');$('#search').removeAttribute('aria-activedescendant');$('#search').value='';}
function renderSearch(){
 const q=$('#search').value.trim(),found=searchPlaces(view==='future'?futureOnly(places):places,q);$('#search-results').hidden=!q;$('#search').setAttribute('aria-expanded',String(!!q));$('#search').removeAttribute('aria-activedescendant');
 $('#search-results').innerHTML=found.length?found.map((p,i)=>'<button id="search-option-'+i+'" role="option" aria-selected="false" tabindex="-1" data-open="'+p.id+'"><strong>'+esc(p.name)+'</strong><small>'+esc(p.future?'Coming soon':p.parentName||p.village||'Sterling Ranch')+'</small></button>').join(''):'<p role="status">'+(view==='future'?'No matching future project. Try school, library or a village name.':'No matching place. Try pickleball, playground or a place name.')+'</p>';
 $('#search-announcement').textContent=q?found.length+' matching '+(view==='future'?'future projects':'places')+'. Use the arrow keys to choose.':'';
}
function searchKey(e){
 const list=$('#search-results'),options=[...list.querySelectorAll('[role="option"]')];
 if(e.key==='Escape'){list.hidden=true;$('#search').setAttribute('aria-expanded','false');$('#search').removeAttribute('aria-activedescendant');return;}
 if(list.hidden||!options.length)return;
 let index=options.findIndex(o=>o.id===$('#search').getAttribute('aria-activedescendant'));
 if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();index=(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;for(const [i,o] of options.entries())o.setAttribute('aria-selected',String(i===index));$('#search').setAttribute('aria-activedescendant',options[index].id);options[index].scrollIntoView({block:'nearest'});}
 if(e.key==='Enter'){e.preventDefault();select(options[Math.max(0,index)].dataset.open,true);}
}
function routeSvg(r){const vb=r.viewBox||trails.overview;return `<svg class="route-sketch" viewBox="${vb.join(' ')}" role="img" aria-label="${esc(r.name)} on CAB’s walking map"><image href="assets/cab-trail-map.png" width="${trails.imageSize[0]}" height="${trails.imageSize[1]}"/><g fill="none" stroke="${esc(r.color)}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${r.paths.map(path=>`<polyline points="${path.map(p=>p.join(',')).join(' ')}"/>`).join('')}</g>${(trails.annotationUpdates||[]).map(a=>`<g><rect x="${a.box[0]}" y="${a.box[1]}" width="${a.box[2]}" height="${a.box[3]}" fill="#f0f2e8"/><text x="${a.box[0]+3}" y="${a.box[1]+10}" fill="#24443f" font-size="7" font-family="Arial,sans-serif">${a.lines.map((t,i)=>`<tspan x="${a.box[0]+3}" dy="${i?10:0}">${esc(t)}</tspan>`).join('')}</text></g>`).join('')}</svg>`;}
function renderWalks(){$('#walk-list').innerHTML=trails.routes.map(r=>`<article class="walk-card" data-route-id="${r.id}">${routeSvg(r)}<p class="eyebrow">${esc(r.area)} / ${esc(r.type)}</p><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="route-stats"><span>${r.miles} mi</span><span>${Math.round(r.miles*20)}–${Math.round(r.miles*30)} min before stops</span></div><p><strong>Start:</strong> ${esc(r.start)}</p><button class="primary" data-route="${r.id}">Open walking guide <span>↗</span></button></article>`).join('');}
function showRoute(id){const r=trails.routes.find(r=>r.id===id);$('#route-content').innerHTML=`<p class="eyebrow">${esc(r.area)} / CAB WALKING GUIDE</p><h2 id="route-title">${esc(r.name)}</h2>${routeSvg(r)}<p>${esc(r.description)}</p><p class="route-distance">${r.miles} miles · ${esc(trails.distanceNote)}</p><p><strong>Start:</strong> ${esc(r.start)}</p><ol class="route-steps">${r.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p><strong>Finish:</strong> ${esc(r.finish)}</p><div class="route-nearby">${r.nearbyPlaceIds.filter(id=>byId.has(id)).map(id=>`<button data-route-place="${id}">${esc(byId.get(id).name)} ↗</button>`).join('')}</div><p class="source-footnote">${esc(trails.mapNote)}</p><div class="source-actions">${link({label:'Official CAB trail map',url:trails.source.url})}${link({label:'Current trail information',url:trails.source.listingUrl})}</div>`;$('#route-dialog').showModal();}
function projectDetails(p){const update=local.projects.find(x=>x.id===p.id);const nested=places.filter(c=>c.parentId===p.id&&c.future);return `<article class="project-card" id="project-${p.id}" data-project-id="${p.id}"><span class="project-status">${esc(update?.status||p.status||'Planned')}</span><p class="eyebrow">${esc(p.village||'STERLING RANCH')}</p><h3>${esc(update?.name||p.name)}</h3><p>${esc(update?.summary||summary(p))}</p>${update?`<ul class="visit-list">${update.details.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><div class="source-actions">${link({label:update.sourceLabel,url:update.url})}</div><p class="source-footnote">${esc(update.locationNote)}</p>`:visit(p)}${nested.length?`<details class="nested"><summary>Plans within this place · ${nested.length}</summary>${nested.map(c=>`<h4 id="project-detail-${c.id}">${esc(c.name)}</h4><p>${esc(summary(c))}</p>${visit(c)}`).join('')}</details>`:''}</article>`;}
function renderFuture(){futureMap.render();}
function renderDirectoryGrid(){const villages=[...new Set(roots.map(p=>p.village||'Sterling Ranch'))];$('#area-filter').innerHTML='<option value="all">Every area</option>'+villages.map(v=>`<option>${esc(v)}</option>`).join('');const draw=()=>{$('#all-places').innerHTML=roots.filter(p=>$('#area-filter').value==='all'||p.village===$('#area-filter').value).map(p=>`<button class="place-card" data-open="${p.id}" data-root-id="${p.id}"><span class="eyebrow">${esc(p.village||'Sterling Ranch')}</span><strong>${esc(p.name)}</strong><small>${descendants(p.id,places).length?descendants(p.id,places).length+(descendants(p.id,places).length===1?' amenity inside':' places & amenities inside'):'Details & official sources'}${located.has(p.id)?'':' · map position to confirm'}</small><span class="card-arrow">↗</span></button>`).join('');};$('#area-filter').addEventListener('change',draw);draw();}
const futureMap=createFutureMap({places,roots,point:id=>artAnchors[id]||located.get(id)?.imagePixels,details:projectDetails,onChange:()=>saveNavigation()});
const camera=createFocus({roots,point,onReset:()=>{discovery.reset();saveNavigation();}});
const discovery=createDiscovery({places,roots,trails,models,located,selected:()=>selected,select,showRoute,setView,routeSvg,focusVillage:name=>camera.village(name),focusState:()=>camera.state(),point,onChange:()=>saveNavigation()});
document.addEventListener('click',e=>{if(view==='neighborhood'&&e.target.closest('[data-open]'))pendingReturnMap={discovery:discovery.state(),focus:camera.snapshot()};},true);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){if(b.dataset.view==='place'&&view==='neighborhood')returnMap={discovery:discovery.state(),focus:camera.snapshot()};setView(b.dataset.view);}if(b.dataset.select)select(b.dataset.select);if(b.dataset.open)select(b.dataset.open,true);if(b.dataset.detail)openDetail(b.dataset.detail);if(b.dataset.hotspot)openDetail(b.dataset.hotspot);if('detailBack'in b.dataset){detail=null;renderDirectory();renderHotspots();$('#directory').focus({preventScroll:true});saveNavigation();}if('group'in b.dataset){group=Number(b.dataset.group);detail=null;renderPlace();$('.inside-amenities')?.scrollIntoView({block:'start',behavior:scrollBehavior()});$('.category-tabs [data-group="'+group+'"]')?.focus({preventScroll:true});}if(b.dataset.route)showRoute(b.dataset.route);if(b.dataset.routePlace){$('#route-dialog').close();select(b.dataset.routePlace,true);}if(b.dataset.close)$('#'+b.dataset.close).close();if('amenitiesJump'in b.dataset)$('.inside-amenities')?.scrollIntoView({block:'start',behavior:scrollBehavior()});if('visitJump'in b.dataset){$('#directory').focus({preventScroll:true});$('#directory').scrollIntoView({block:'start',behavior:scrollBehavior()});}if('seeArt'in b.dataset){$('#model-stage').scrollIntoView({block:'start',behavior:scrollBehavior()});}if('copyPlace'in b.dataset)copyLink();if('returnMap'in b.dataset)returnToMap();if(b.dataset.group)saveNavigation();});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.modelSelect){showingReference=false;select(b.dataset.modelSelect,true);}if(b.dataset.modelMedia){showingReference=b.dataset.modelMedia==='photo';renderPlace();document.querySelector('[data-model-media="'+b.dataset.modelMedia+'"]')?.focus({preventScroll:true});saveNavigation();}});
$('#back-to-map').onclick=returnToMap;$('#context-map').onclick=()=>{returnMap=null;camera.place(selected,byId.get(selected).name);returnToMap();};$('#roof-toggle').onclick=()=>{opened=!opened;renderPlace();saveNavigation();};$('#zoom-in').onclick=()=>{camera.zoom(.25);saveNavigation();};$('#zoom-out').onclick=()=>{camera.zoom(-.25);saveNavigation();};$('#reset-map').onclick=()=>{camera.clear();discovery.reset();saveNavigation();};
$('#source-toggle').onclick=()=>{source=!source;$('#source-art').hidden=!source;$('#source-toggle').setAttribute('aria-pressed',String(source));$('.map-topnote small').textContent=source?'Saved source geometry · approximate facility coordinates':'Illustrated overview · approximate placement';renderMap();focusMap();saveNavigation();};
$('#about-open').onclick=$('#sources-open').onclick=()=>$('#about-dialog').showModal();
$('#search').addEventListener('input',renderSearch);$('#search').addEventListener('keydown',searchKey);
$('#inventory-count').textContent=`${places.length} listings · ${roots.length} destinations · ${trails.routes.length} walking guides`;document.body.dataset.coverage='full-saved-atlas-area';document.body.dataset.placeCount=places.length;document.body.dataset.rootCount=roots.length;document.body.dataset.routeCount=trails.routes.length;
const art=$('#landscape-art');const loaded=()=>$('#image-status').hidden=art.complete&&art.naturalWidth>0;art.addEventListener('load',loaded);art.addEventListener('error',()=>{$('#image-status').textContent='The illustration could not load. The directory and source map are still available.';$('#source-art').hidden=false;});loaded();
renderDirectoryGrid();renderMap();restoreNavigation(readNavigation(location.search));navigationReady=true;saveNavigation(true);
addEventListener('popstate',e=>restoreNavigation(e.state?.atlas||readNavigation(location.search)));
$('#building-intact').addEventListener('load',renderHotspots);addEventListener('resize',()=>positionHotspots($('#building'),$('#building-intact')));
$('#place-picker').addEventListener('change',e=>select(e.target.value,true));
document.querySelector('.skip').addEventListener('click',()=>{const target=document.querySelector($('.skip').getAttribute('href'));target.setAttribute('tabindex','-1');target.focus();});
async function copyLink(){saveNavigation(true);await new Promise(resolve=>queueMicrotask(resolve));const url=location.href;try{await navigator.clipboard.writeText(url);$('#share-status').textContent='Link copied';}catch{const field=$('#share-url');field.hidden=false;field.value=url;field.focus();field.select();$('#share-status').textContent='Copy this link';}}

} catch(error){$('#image-status').hidden=false;$('#image-status').textContent='The atlas could not load its saved directory. Please reload.';console.error(error);}
