const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('C:/Users/mar15/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='https://sterling-ranch-food-truck-chat-staging.up.railway.app',root=path.resolve(__dirname,'../..'),live=process.env.AUDIT_LIVE==='1',files={'/':'index.html','/calendar':'calendar.html','/community-assistant':'rules-assistant.html','/food-truck':'food-truck.html'};
(async()=>{const b=await chromium.launch({channel:'chrome'});try{
async function page(url,width=390,height=844){const p=await b.newPage({viewport:{width,height},timezoneId:'Asia/Tokyo'});if(!live)await p.route(base+'/**',r=>{const u=new URL(r.request().url()),local=path.join(root,'public',files[u.pathname]||u.pathname.slice(1));return !u.pathname.startsWith('/api/')&&fs.existsSync(local)&&fs.statSync(local).isFile()?r.fulfill({path:local}):r.fallback()});return p;}
const fixture={status:'partial',events:[{title:'Already started fixture',date:'2026-09-10',time:'13:00',url:'/community-calendar'},{title:'Later today fixture',date:'2026-09-10',time:'15:00',url:'/community-calendar'},{title:'Unspecified time fixture',date:'2026-09-10',url:'/community-calendar'},{title:'Tomorrow fixture',date:'2026-09-11',time:'09:00',url:'/community-calendar'},{title:'Old fixture',date:'2026-09-09',time:'09:00',url:'/community-calendar'}]};
for(const url of ['/calendar','/']){const p=await page(url);await p.clock.install({time:new Date('2026-09-10T20:00:00Z')});await p.route('**/api/community/events',r=>r.fulfill({json:fixture}));await p.goto(base+url);await p.locator('#briefing-events[aria-busy="false"]').waitFor();assert(await p.locator('#briefing-events').evaluate(e=>e.lastElementChild.classList.contains('calendar-notice')));assert.equal(await p.getByRole('heading',{name:'Old fixture',exact:true}).count(),0);assert(await p.getByRole('heading',{name:'Later today fixture',exact:true}).isVisible());assert(await p.getByRole('heading',{name:'Unspecified time fixture',exact:true}).isVisible());if(url==='/calendar'){assert(await p.getByRole('heading',{name:'Today',exact:true}).isVisible());assert(await p.getByRole('heading',{name:'Tomorrow',exact:true}).isVisible());assert(!(await p.getByRole('heading',{name:'Already started fixture',exact:true}).isVisible()));await p.locator('.calendar-earlier summary').click();assert(await p.getByRole('heading',{name:'Already started fixture',exact:true}).isVisible());}else{assert(await p.locator('#briefing-next-event').isVisible());assert((await p.locator('#briefing-next-event').boundingBox()).y<(await p.locator('#today-assistant').boundingBox()).y);}await p.screenshot({path:path.join(__dirname,(live?'staging':'candidate')+'-calendar-fixture'+(url==='/'?'-home':'')+'.png'),fullPage:true});await p.close();}
for(const payload of [{status:'ok',events:[]},null]){const p=await page('/calendar');await p.route('**/api/community/events',r=>r.fulfill(payload?{json:payload}:{status:503,json:{error:'Fixture unavailable'}}));await p.goto(base+'/calendar');await p.locator('#briefing-events[aria-busy="false"]').waitFor();assert(await p.locator('.calendar-notice a').isVisible());assert.match(await p.locator('.calendar-notice').innerText(),payload?/No upcoming events/:/couldn’t load/);await p.close();}
for(const url of ['/food-truck','/community-assistant']){const p=await page(url);await p.route('**/api/{community,rules}/ask',r=>{assert.equal(r.request().postDataJSON().isTest,true);return r.fulfill({json:{answer:'Browser-only example selection fixture.',sources:[],confidence:{canAnswer:false}}})});await p.goto(base+url+'?test=1');const assistant=url==='/community-assistant';await p.locator(assistant?'#testModeBanner':'.food-result').waitFor({timeout:35000});if(assistant){await p.locator('#startersToggle').click();await p.locator('#rulesStarters button').first().click();await p.waitForFunction(()=>document.querySelectorAll('.rules-message').length>=2);assert(await p.locator('#rulesStarters').evaluate(e=>e.hidden));}
await p.setViewportSize({width:390,height:480});await p.waitForTimeout(250);const input=p.locator(assistant?'#rulesQuestion':'#questionInput');await input.fill('Browser-only keyboard sizing check');assert(await input.evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));assert(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));assert((await p.locator(assistant?'#rulesScroll':'#messages').boundingBox()).height>160);await p.screenshot({path:path.join(__dirname,(live?'staging':'candidate')+'-short-viewport-'+(assistant?'assistant':'food')+'.png')});await p.setViewportSize({width:390,height:844});await p.waitForTimeout(200);assert(await p.locator('.site-footer').isVisible());await p.close();}

for(const kind of ['structured','multiple','missing-menu','warning']){const p=await page('/food-truck',1024,768);const listing={name:'Browser fixture truck',truck:'Browser fixture truck',menu:{items:[{name:'Fixture menu item',description:'Browser-only description',price:'$10'}]}};const data={...listing,text:'Browser-only fixture response prose.',friendlyDate:'Fixture date',sourceUrl:'https://sterlingranchcab.com/',checkedAt:'2026-09-10T12:00:00Z'};if(kind==='multiple')data.trucks=[listing];if(kind==='missing-menu')data.menu={items:[]};if(kind==='warning')data.warning='Fixture warning';await p.route('**/api/ask?*',r=>r.fulfill({json:data}));await p.goto(base+'/food-truck');await p.locator('.food-result').waitFor();const answer=p.locator('.answer-text');if(['structured','multiple'].includes(kind)){assert(!(await answer.isVisible()));assert(await p.locator('.food-response-details').evaluate(e=>{const menu=e.parentElement.querySelector('.menu-section:not(.hidden)');return Boolean(menu.compareDocumentPosition(e)&Node.DOCUMENT_POSITION_FOLLOWING)}));await p.locator('.food-response-details summary').click();assert(await answer.isVisible());}else{assert(await answer.isVisible());assert.equal(await p.locator('.food-response-details').count(),0);}if(kind==='multiple')await p.screenshot({path:path.join(__dirname,(live?'staging':'candidate')+'-food-structured.png')});await p.close();}
const weatherPage=await page('/');await weatherPage.route('**/api/weather',r=>r.fulfill({json:{status:'unavailable',periods:[]}}));await weatherPage.goto(base+'/');await weatherPage.locator('#briefing-weather[aria-busy="false"]').waitFor();assert.match(await weatherPage.locator('#briefing-weather').innerText(),/temporarily unavailable/);assert(await weatherPage.getByRole('link',{name:'Full forecast'}).isVisible());assert.equal(await weatherPage.locator('.briefing-essentials a').count(),3);await weatherPage.close();
console.log('Passed Calendar partial, empty, unavailable, Denver time, earlier-started, unknown-time, mobile priorities, example selection, and short viewport checks. All Assistant responses were browser-only fixtures.');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
